version: '3.9'

services:
  db:
    image: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - .env

  wiki:
    build:
      context: ./WikiDocker
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db